CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS video (
    id UUID PRIMARY KEY UNIQUE NOT NULL,
    title VARCHAR(256) NOT NULL UNIQUE,
    url VARCHAR NOT NULL,
    description VARCHAR NOT NULL
);